name: dfns_sdk_flutter
description: "Dfns Flutter SDK"

version: 0.0.4

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  json_annotation: ^4.9.0
  passkeys: ^2.0.8

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
